version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - backend-network

  redis:
    image: redis:7.2
    container_name: sesac-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - backend-network

volumes:
  redis-data:

networks:
  backend-network: