name: Deploy Backend 

on:
  push:
    paths:
      - 'backend/**'
      - 'backend/docker-compose.yml'
      - '.github/workflows/backend-deploy.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}         # EC2 퍼블릭 IP 또는 도메인
          username: ${{ secrets.EC2_USER }}     # ec2-user, ubuntu 등
          key: ${{ secrets.EC2_KEY }}           # SSH private key (GitHub Secrets에 등록)
          script: |
            cd ~/SeSAC-ticket/backend
            git pull origin main

            docker-compose down
            docker-compose up -d --build
